config/routes.rb
Rails.application.routes.draw do
#	get 'undelete', :to => 'articles#undelete'
#	resources :articles
	get 'keywords', to: "welcome#index", as: :keywords
	resources :articles do
	  member do
	    put 'undestroy'
	  end
	  collection do
	    get 'undelete'
	    get 'embed'
	  end
	end
 
  	root 'welcome#index'
	get 'index_rus', to: "welcome#index_rus", as: :index_rus
	get 'index', to: "welcome#index", as: :index
end

app/models/article.rb
class Article < ApplicationRecord
  def keywords=(value)
    return super value.reject!(&:blank?).join(", ") if value.is_a?(Array)

    super
  end

  self.per_page = 9
  include Filterable
  validates :title_rus, presence: true, length: { minimum: 5 }
  validates :country, presence: true, length: { minimum: 2 }
  validates :category, presence: true
  validates :src_url, presence: true
  validates :keywords, presence: true
  validates :text, presence: true, length: { minimum: 5 }
  validates :date, presence: true

  scope :country, -> (country) { where country: country }
  scope :category, -> (category) { where category: category }
  scope :src_url, -> (src_url) { where('src_url like ?', "%#{src_url}%")}
  scope :date, -> (date) { where date: date }
  scope :lang, -> (lang) { where lang: lang }
  scope :keywords, -> (keywords) { where('keywords like ?', "%#{keywords}%")}
  scope :keywords2, -> (keywords2) { where('keywords2 like ?', "%#{keywords2}%")}
  scope :title_rus, -> (title_rus) { where('title_rus like ?', "%#{title_rus}%")}
  scope :title, -> (title) { where('title LIKE ?', "%#{title}%")}
  scope :rel, -> (rel) { where rel: rel }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  PRIORITY_COUNTRIES = %w[RU BR IN CN ZA]
  after_filter :allow_iframe, only: [:embed]
  http_basic_authenticate_with name: "edt", password: "pass", except: [:index, :show, :embed]

  def index
    if params[:search] == nil
      @articles = Article.filter(params.slice(:category, :country, :src_url, :date, :lang, :keywords, :keywords2, :title, :title_rus, :rel)).where(is_active: true).order('id DESC').paginate(:page => params[:page], :per_page => 9)
    else
      @articles = Article.search(params[:search], :without => {:is_active => false}, :page => params[:page], :per_page => 9, :order => :id)
    end

    @countries = ISO3166::Country.countries.sort_by do |country|
      priority_index = PRIORITY_COUNTRIES.index(country.alpha2)
      priority_index.present? ? priority_index.to_s : country.name
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @keywordslst = [ 'bio',
	'brics+',
	'concluded_agreements',
	'digital',
	'ecology',
	'economic_challenges',
	'emerging_market',
	'expert_opinion',
	'fas',
	'foreign_ministers_meeting',
	'global_governance',
	'imf',
	'innovations',
	'investments',
	'media',
	'mofa',
	'movie',
	'national_security',
	'ndb',
	'obor',
	'off_docs',
	'pharmacy',
	'quotation',
	'rating',
	'research',
	'sergey_lavrov',
	'social_issues',
	'space',
	'speech',
        'summit',
	'sustainable_development',
	'terrorism',
	'top_level_meeting',
	'trade_relations',
	'un',
	'unclear',
	'vladimir_putin',
	'wang_yi',
	'wto',
	'xi_jinping',
	'xiamen_summit',
        'political_issues',
        'narendra_modi',
        'cyril_ramaphosa',
        'business_council',
        'think_tank_council',
	'cooperation',
	'declaration',
	'partnership',
	'chairmanship',
  'jair_bolsonaro',
  'covid-19'
    ]
    @article = Article.new
    respond_to do |format|
      format.html
      format.json { render json: @keywordslst.to_json }
    end
  end

  def edit
    @article = Article.find(params[:id])
    @keywordslst = [ 'bio',
	'brics+',
	'concluded_agreements',
	'digital',
	'ecology',
	'economic_challenges',
	'emerging_market',
	'expert_opinion',
	'fas',
	'foreign_ministers_meeting',
	'global_governance',
	'imf',
	'innovations',
	'investments',
	'media',
	'mofa',
	'movie',
	'national_security',
	'ndb',
	'obor',
	'off_docs',
	'pharmacy',
	'quotation',
	'rating',
	'research',
	'sergey_lavrov',
	'social_issues',
	'space',
	'speech',
        'summit',
	'sustainable_development',
	'terrorism',
	'top_level_meeting',
	'trade_relations',
	'un',
	'unclear',
	'vladimir_putin',
	'wang_yi',
	'wto',
	'xi_jinping',
	'xiamen_summit',
        'political_issues',
        'narendra_modi',
        'cyril_ramaphosa',
        'business_council',
        'think_tank_council',
	'cooperation',
	'declaration',
	'partnership',
	'chairmanship',
	'jair_bolsonaro',
  'covid-19'
    ]
  end

  def create
    @article = Article.new(article_params)

    @article.lang = @article.title.blank? ? 'rus' : 'eng'

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    @article.lang = @article.title.blank? ? 'rus' : 'eng'

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.update(:is_active => false)

    redirect_to articles_path
  end

  def undelete
    @articles = Article.where(is_active: false).paginate(:per_page => 15, :page => params[:page])
  end

  def embed
    @rese, @resr = 0
    if params[:search] == nil
      @articles = Article.where(is_active: true).order('id DESC').paginate(:page => params[:page], :per_page => 15)
    else
      @articles = Article.search(params[:search], :without => {:is_active => false}, :page => params[:page], :per_page => 15, :order => "id DESC")
      @rese = Article.search(params[:search], :without => {:is_active => false, :lang => 'rus'}).count
      @resr = Article.search(params[:search], :without => {:is_active => false, :lang => 'eng'}).count
    end
  end

  def undestroy
    @article = Article.find(params[:id])
    @article.update(:is_active => true)

    redirect_to undelete_articles_path
  end


  private
    def article_params
      params.require(:article).permit(:title_rus, :title, :date, :src_url, :country, :author, :category, :keywords2, :text, :lang, :rel, :keywords)
    end

    def allow_iframe
      response.headers.delete "X-Frame-Options"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: { class: "form-horizontal" } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation" class="alert alert-warning" role="alert">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :"Title_(russian)", class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_field :title_rus, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :"Title_(english)", class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_field :title, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date, class: 'col-md-1 control-label' %>
    <div class="col-md-3">
      <%= f.date_field :date, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :source_url, class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_field :src_url, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :"Country of origin", class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.country_select :country, { priority_countries: %w(RU BR IN CN ZA), prompt: ''}, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :author, class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_field :author, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :category, class: 'col-md-1 control-label' %>
    <div class="col-md-3">
      <%= f.select :category, [
        '',
        '1 международные отношения',
        '2 экономика',
        '3 внутренняя политика',
        '4 мир труда',
        '5 документы',
        '6 другие материалы',
        '1 international relations',
        '2 investment and finance',
        '3 political events',
        '4 world of work',
        '5 documents',
        '6 other materials'
      ], {}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :keywords, class: 'col-md-1 control-label' %>
    <div class="col-md-3">
      <%= f.text_field :keywords, id: "keywords", data: { role: 'tagsinput' } %>
      <!-- Нужно передать функции идентификатор поля('#keywords')
      и путь к json коллекции.
      смотри пример в контроллере 'articles#new'
      Сама функция находится в assets/javascript/application.js:28
      -->
    	<%= javascript_tag do %>
        TagsInput('#keywords', "<%= new_article_url %>.json")
    	<% end %>
      <%= f.label "Keywords: " %><%= @keywordslst %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :keywords2, class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_field :keywords2, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :relevance, class: 'col-md-1 control-label' %>
    <div class="col-md-3">
      <%= f.select :rel, [
        '',
        '0',
        '1',
        '2',
        '3',
        '4',
        '5'
      ], {}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :text, class: 'col-md-1 control-label' %>
    <div class="col-md-11">
      <%= f.text_area :text, :rows => 20, style: 'width:100%;', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-1 col-md-offset-1">
      <%= f.submit :Submit, class: 'btn btn-primary btn-block' %>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>Edit entry</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <%= link_to 'Back', articles_path %>
        </div>
    </div>
</div>

app/views/articles/embed.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= form_tag embed_articles_path, :enforce_utf8 => false, :method => 'get', :class => 'form-inline'  do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control input-sm' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Search", :name => nil, class: 'btn btn-primary btn-sm' %>
        </div>
        <div class="form-group">
          Eng: <%= @rese %>, Rus: <%= @resr %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="table-responsive">
      <br>
      <table class="table-borderless table-striped table-condensed">
        <tr>
          <th width="3%">ID</th>
          <th width="40%">Title (russian)</th>
          <th width="40%">Title (english)</th>
          <th>Author</th>
          <th>Date</th>
          <th>Link</th>
        </tr>

        <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.id %>
            </td>
            <td>
              <%= link_to article.title_rus, article_path(article) %>
            </td>
            <td>
              <%= link_to article.title, article_path(article) %>
            </td>
            <td>
              <%= link_to article.author, article_path(article) %>
            </td>
            <td>
              <%= article.date %>
            </td>
            <td>
              <%= link_to URI(article.src_url).host, article.src_url %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= will_paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Listing entries</h1>
      <%= link_to 'New entry', new_article_path %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12">
      <h1>Sphinx search</h1>
      <%= form_tag articles_path, :enforce_utf8 => false, :method => 'get', :class => 'form-inline'  do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: 'form-control input-sm' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Search", :name => nil, class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <br>
      <table class="table table-bordered table-striped table-condensed" width="100%">
        <tr>
          <th>ID</th>
          <th width="15%">Title (russian)</th>
          <th width="15%">Title (english)</th>
          <th>Date</th>
          <th>Source</th>
          <th>Country of origin</th>
          <th>Category</th>
          <th>Keywords</th>
          <th>Keywords 2</th>
          <th>Language</th>
          <th>Relevance</th>
          <th colspan='3' class="text-center">Controls</th>
        </tr>

        <%= form_tag articles_path, :enforce_utf8 => false, :method => 'get' do %>
          <tr>
            <th></th>
            <th>
              <%= text_field_tag :title_rus, params[:title_rus], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= text_field_tag :title, params[:title], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= date_field_tag :date, params[:date], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= text_field_tag :src_url, params[:src_url], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= select_tag :country, options_from_collection_for_select(@countries, 'name', 'name', params[:country]), :include_blank => true, class: 'form-control input-sm' %>
            </th>
            <th>
              <%= select_tag :category, options_for_select([
                '',
                '1 международные отношения',
                '2 экономика',
                '3 внутренняя политика',
                '4 мир труда',
                '5 документы',
                '6 другие материалы',
                '1 international relations',
                '2 investment and finance',
                '3 political events',
                '4 world of work',
                '5 documents',
                '6 other materials'
              ], params[:category]), class: 'form-control input-sm' %>
            </th>
            <th>
              <%= text_field_tag :keywords, params[:keywords], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= text_field_tag :keywords2, params[:keywords2], class: 'form-control input-sm' %>
            </th>
            <th>
              <%= select_tag :lang, options_for_select(['', 'rus', 'eng'], params[:lang]), class: 'form-control input-sm' %>
            </th>
            <th>
              <%= select_tag :rel, options_for_select([
                '',
                '0',
                '1',
                '2',
                '3',
                '4',
                '5'], params[:rel]), class: 'form-control input-sm' %>
            </th>
            <th class="text-center" colspan ='3'>
              <%= submit_tag "Filter", :name => nil, class: 'btn btn-primary btn-sm' %>
            </th>
          </tr>
        <% end %>

        <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.id %>
            </td>
            <td>
              <%= article.title_rus %>
            </td>
            <td>
              <%= article.title %>
            </td>
            <td>
              <%= article.date %>
            </td>
            <td>
              <%= link_to URI(article.src_url).host, article.src_url %>
            </td>
            <td>
              <%= article.country %>
            </td>
            <td>
              <%= article.category %>
            </td>
            <td>
              <%= article.keywords %>
            </td>
            <td>
              <%= article.keywords2 %>
            </td>
            <td>
              <%= article.lang %>
            </td>
            <td>
              <%= article.rel %>
            </td>
            <td>
              <%= link_to 'Show', article_path(article) %>
            </td>
            <td>
              <%= link_to 'Edit', edit_article_path(article) %>
            </td>
            <td>
              <%= link_to 'Delete', article_path(article),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= will_paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h1>New entry</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <%= render 'form' %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">        
            <%= link_to 'Back', articles_path %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
<br>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-bordered table-hover">
      <tbody>
        <tr>
          <td><strong>Title (russian):</strong></td>
          <td><%= @article.title_rus %></td>
        </tr>

        <tr>
          <td><strong>Title (english):</strong></td>
          <td><%= @article.title %></td>
        </tr>

        <tr>
          <td><strong>Date:</strong></td>
          <td><%= @article.date %></td>
        </tr>

        <tr>
          <td><strong>Link:</strong></td>
          <td><%= link_to URI(@article.src_url).host, @article.src_url %></td>
        </tr>

        <tr>
          <td><strong>Country of origin:</strong></td>
          <td><%= @article.country %></td>
        </tr>

        <tr>
          <td><strong>Author:</strong></td>
          <td><%= @article.author %></td>
        </tr>

        <tr>
          <td><strong>Category:</strong></td>
          <td><%= @article.category %></td>
        </tr>

        <tr>
          <td><strong>Keywords:</strong></td>
          <td><%= @article.keywords %></td>
        </tr>

        <tr>
          <td><strong>Keywords 2:</strong></td>
          <td><%= @article.keywords2 %></td>
        </tr>

        <tr>
          <td><strong>Relevance:</strong></td>
          <td><%= @article.rel %></td>
        </tr>

        <tr>
          <td><strong>Text:</strong></td>
          <td><%= @article.text %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Edit', edit_article_path(@article) %> |
      <%= link_to 'Back', articles_path %>
    </div>
  </div>

</div>

app/views/articles/undelete.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1>Listing entries</h1>
            <%= link_to 'Back', articles_path %>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered table-striped table-condensed">
              <tr>
                <th>ID</th>
                <th width="15%">Title (russian)</th>
                <th width="15%">Title (english)</th>
                <th>Date</th>
                <th>Source</th>
                <th>Country</th>
                <th>Category</th>
                <th>Keywords</th>
                <th colspan="3" class="text-center">Controls</th>
              </tr>

              <% @articles.each do |article| %>
                <tr>
                  <td><%= article.id %></td>
                  <td><%= article.title_rus %></td>
                  <td><%= article.title %></td>
                  <td><%= article.date %></td>
                  <td><%= link_to URI(article.src_url).host, article.src_url %></td>
                  <td><%= article.country %></td>
                  <td><%= article.category %></td>
                  <td><%= article.keywords %></td>
                  <td><%= link_to 'Show', article_path(article) %></td>
                  <td><%= link_to 'Edit', edit_article_path(article) %></td>
                  <td><%= link_to 'Undelete', undestroy_article_path(article),
                          method: :put,
                          data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </table>
        </div>
    </div>
        
    <div class="row">
        <div class="col-md-12">
            <%= will_paginate @article %>
        </div>
    </div>

</div>