config/routes.rb
Rails.application.routes.draw do
#	get 'undelete', :to => 'articles#undelete'
#	resources :articles
	get 'keywords', to: "welcome#index", as: :keywords
	resources :articles do
	  member do
	    put 'undestroy'
	  end
	  collection do
	    get 'undelete'
	    get 'embed'
	  end
	end
 
  	root 'welcome#index'
	get 'index_rus', to: "welcome#index_rus", as: :index_rus
	get 'index', to: "welcome#index", as: :index
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index

    @articles = Article
    @sume = 0
    @sumr = 0
    param = params[:search]

    @keywordslst = [ 'bio',
	'brics+',
	'concluded_agreements',
	'digital',
	'ecology',
	'economic_challenges',
	'emerging_market',
	'expert_opinion',
	'fas',
	'foreign_ministers_meeting',
	'global_governance',
	'imf',
	'innovations',
	'investments',
	'media',
	'mofa',
	'movie',
	'national_security',
	'ndb',
	'obor',
	'off_docs',
	'pharmacy',
	'quotation',
	'rating',
	'research',
	'sergey_lavrov',
	'social_issues',
	'space',
	'speech',
        'summit',
	'sustainable_development',
	'terrorism',
	'top_level_meeting',
	'trade_relations',
	'un',
	'unclear',
	'vladimir_putin',
	'wang_yi',
	'wto',
	'xi_jinping',
	'xiamen_summit',
        'political_issues',
        'narendra_modi',
        'cyril_ramaphosa',
        'business_council',
        'think_tank_council',
	'cooperation',
	'declaration',
	'partnership',
	'chairmanship',
	'jair_bolsonaro',
  'covid-19'
    ]
    @keywordslst.sort!
	
    @testingref = []
    @graph = []
    @data = []

    if !params[:search2] then
      params[:search2] = 'brics+'
    end

    if params[:search2] then
      axX = 0
      axY = 0
      cnt = 0
      angle = [36, 72, 108, 144, 180, 216, 252, 288, 324, 360]

      @keywordslst.each do |c|
        if (c != params[:search2]) then
          freq = Article.search(c, :without => {:is_active => false}, :per_page => 9999).count
          dist = Article.search(c+' AND '+params[:search2], :without => {:is_active => false}, :per_page => 9999).count
          dist = 1000/dist.to_f
          @data.push([c, dist, freq])
        end
      end

      @data.sort! {|a,b| a[1] <=> b[1]}
      while @data.count > 10 do
        @data.pop
      end
      @data.shuffle!

      @data.each do |c|
        axY = c[1] * Math.sin(angle[cnt] * Math::PI/180)
        axX = c[1] * Math.cos(angle[cnt] * Math::PI/180)
        @graph.push(['', axX, axY, c[0], c[2]])
        cnt = cnt+1
      end

      freq = Article.search(params[:search2], :without => {:is_active => false}, :per_page => 9999).count
      @graph.insert(0, ['', 0, 0, params[:search2], freq])
      @graph.insert(0, ['', '', '', 'Category name', 'Mutual occurrences frequency'])

      
    end

    respond_to do |format|
      format.html
      format.json { render json: @keywordslst.to_json }
    end
  end

def index_rus

    @articles = Article
    @sume = 0
    @sumr = 0
    param = params[:search]

    @keywordslst = [ 'bio',
	'brics+',
	'concluded_agreements',
	'digital',
	'ecology',
	'economic_challenges',
	'emerging_market',
	'expert_opinion',
	'fas',
	'foreign_ministers_meeting',
	'global_governance',
	'imf',
	'innovations',
	'investments',
	'media',
	'mofa',
	'movie',
	'national_security',
	'ndb',
	'obor',
	'off_docs',
	'pharmacy',
	'quotation',
	'rating',
	'research',
	'sergey_lavrov',
	'social_issues',
	'space',
	'speech',
        'summit',
	'sustainable_development',
	'terrorism',
	'top_level_meeting',
	'trade_relations',
	'un',
	'unclear',
	'vladimir_putin',
	'wang_yi',
	'wto',
	'xi_jinping',
	'xiamen_summit',
        'political_issues',
        'narendra_modi',
        'cyril_ramaphosa',
        'sa_chairmanship',
        'business_council',
        'think_tank_council',
	'johannesburg_declaration'
    ]
    @keywordslst.sort!
	
    @testingref = []
    @graph = []
    @data = []

    if !params[:search2] then
      params[:search2] = 'brics+'
    end

    if params[:search2] then
      axX = 0
      axY = 0
      cnt = 0
      angle = [36, 72, 108, 144, 180, 216, 252, 288, 324, 360]

      @keywordslst.each do |c|
        if (c != params[:search2]) then
          freq = Article.search(c, :without => {:is_active => false}, :per_page => 9999).count
          dist = Article.search(c+' AND '+params[:search2], :without => {:is_active => false}, :per_page => 9999).count
          dist = 1000/dist.to_f
          @data.push([c, dist, freq])
        end
      end

      @data.sort! {|a,b| a[1] <=> b[1]}
      while @data.count > 10 do
        @data.pop
      end
      @data.shuffle!

      @data.each do |c|
        axY = c[1] * Math.sin(angle[cnt] * Math::PI/180)
        axX = c[1] * Math.cos(angle[cnt] * Math::PI/180)
        @graph.push(['', axX, axY, c[0], c[2]])
        cnt = cnt+1
      end

      freq = Article.search(params[:search2], :without => {:is_active => false}, :per_page => 9999).count
      @graph.insert(0, ['', 0, 0, params[:search2], freq])
      @graph.insert(0, ['', '', '', 'Название категории', 'Частота совместных упоминаний'])

      
    end

    respond_to do |format|
      format.html
      format.json { render json: @keywordslst.to_json }
    end
  end

  private
    def allow_iframe
      response.headers.delete "X-Frame-Options"
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= javascript_tag do %>
     google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawSeriesChart);

    function drawSeriesChart() {

      var data = google.visualization.arrayToDataTable($('.temp_information').data('temp'));

      var options = {
        title: 'Keyword joint occurance map in entire information array',
        bubble: {textStyle: {fontSize: 8}},
	hAxis: { baselineColor: '#000', gridlineColor: '#fff', textPosition: 'none' },
	vAxis: { baselineColor: '#000', gridlineColor: '#fff',textPosition: 'none' }
      };

      var chart = new google.visualization.BubbleChart(document.getElementById('series_chart_div'));
      chart.draw(data, options);
    }
<% end %>

<style>
div.a {
  text-align: center;
}

div.b {
  text-align: left;
}

div.c {
  text-align: right;
} 

div.d {
  text-align: justify;
} 
</style>

<div class="container-fluid">

  <div class="row">
    <div class="col-6 col-md-4">
      <%= form_tag articles_path, :enforce_utf8 => false, :method => 'get', :class => 'form-inline'  do %>
        <div class="form-group">
          <h4>Search BRICS database:</h4>
          <%= text_field_tag :search, params[:search], class: 'form-control input-sm' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Search", :name => nil, class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
    <div class="col-6 col-md-4">
      <div class="a"><h5>Version: rel-05-17-2021</h5></div>
    </div>
    <div class="col-6 col-md-4">
      <div class="c"><h4><%= link_to 'Switch to Russian', :index_rus %></h4></div>
    </div>
  </div>

      <div class="row">
        <div class="col-12">
	      <%= form_tag root_path, :enforce_utf8 => false, :method => 'get' do  %>
                <h4>Build a graph:</h4>
                <%= select_tag :search2, options_for_select(@keywordslst, params[:search2]), { :prompt => "Available options"} %>
	        <%= submit_tag :Submit, class: 'btn btn-primary btn-sm' %>
	      <% end %>
          <br>

          <%= content_tag :div, class: "temp_information", data: {temp: @graph} do %><% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12"><div id="series_chart_div" style="width: 100%; height: 800px;"></div></div>
      </div>

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h4>Total texts in Bulletin</h4>
	  <%= line_chart @articles.where(:lang => 'eng').group_by_month(:date, last: 6).count.map { |x,y| { x => (@sume += y)}}.reduce({}, :merge), curve: false %>
      <h4>Texts spread by subject (monthly slice)</h4>
	  <%= column_chart @articles.where(:lang => 'eng').group(:category).order('category desc').group_by_month(:date, last: 6).count, colors: ["violet", "blue", "green", "yellow", "orange", "red"], stacked: true %>
      <h4>Total Bulletin entries by category (total)</h4>
	  <%= pie_chart @articles.where(:lang => 'eng').group(:category).count, colors: ["red", "orange", "yellow", "green", "blue", "violet"], legend: "right" %>
  
</div>

app/views/welcome/index_rus.html.erb
<%= javascript_tag do %>
     google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawSeriesChart);

    function drawSeriesChart() {

      var data = google.visualization.arrayToDataTable($('.temp_information').data('temp'));

      var options = {
        title: 'Карта совместной встречаемости ключевых слов по всему информационному массиву',
        bubble: {textStyle: {fontSize: 8}},
	hAxis: { baselineColor: '#000', gridlineColor: '#fff', textPosition: 'none' },
	vAxis: { baselineColor: '#000', gridlineColor: '#fff',textPosition: 'none' }
      };

      var chart = new google.visualization.BubbleChart(document.getElementById('series_chart_div'));
      chart.draw(data, options);
    }
<% end %>

<div class="container-fluid">

  <div class="row">
    <div class="col-6">
      <%= form_tag articles_path, :enforce_utf8 => false, :method => 'get', :class => 'form-inline'  do %>
        <div class="form-group">
          <h4>Поиск по базе БРИКС</h4>
          <%= text_field_tag :search, params[:search], class: 'form-control input-sm' %>
        </div>
        <div class="form-group">
          <%= submit_tag "Поиск", :name => nil, class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </div>
    <div class="col-1 offset-5">
      <h4><%= link_to 'Перейти на английский', :index %></h4>
    </div>
  </div>

      <div class="row">
        <div class="col-12">
	      <%= form_tag index_rus_path, :enforce_utf8 => false, :method => 'get' do  %>
            <h4>Постройте диаграмму взаимной встречаемости ключевых слов</h4>
                <%= select_tag :search2, options_for_select(@keywordslst, params[:search2]), { :prompt => "Возможные ключевые слова"} %>
	        <%= submit_tag "Построить", class: 'btn btn-primary btn-sm' %>
	      <% end %>
          <br>

          <%= content_tag :div, class: "temp_information", data: {temp: @graph} do %><% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12"><div id="series_chart_div" style="width: 100%; height: 800px;"></div></div>
      </div>

      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      
      <div class="row">
        <div class="col-12"><h4>Количество текстов, помещённых в Бюллетень</h4></div>
      </div>
      <div class="row">
        <div class="col-12"><%= line_chart @articles.where(:lang => 'rus').group_by_month(:date, last: 6).count.map { |x,y| { x => (@sumr += y)}}.reduce({}, :merge) %></div>
      </div>
      <div class="row">
        <div class="col-12"><h4>Распределение текстов по тематическим разделам (месячный разрез)</h4></div>
        <div class="col-12"><%= column_chart @articles.where(:lang => 'rus').group(:category).order('category desc').group_by_month(:date, last: 6).count, colors: ["violet", "blue", "green", "yellow", "orange", "red"], stacked: true %></div>
      </div>
      <div class="row">
        <div class="col-12"><h4>Количество текстов по тематическим разделам Бюллетеня (всего)</h4></div>
	    <div class="col-12"><%= pie_chart @articles.where(:lang => 'rus').group(:category).count, colors: ["red", "orange", "yellow", "green", "blue", "violet"], legend: "right" %></div>
      </div>
  
</div>